import type { TokenPlan } from "@/lib/types";

export const TOKENS: TokenPlan[] = [
  {
    ticker: "ADA",
    symbol: "ADAUSDT",
    digits: 4,
    invalidation: 0.13,
    zones: [
      { label: "Compra", low: 0.2, high: 0.215, pct: 40 },
      { label: "Add", low: 0.138, high: 0.16, pct: 60 },
    ],
    tps: [
      { label: "TP1", price: 2 },
      { label: "TP2", price: 3.09 },
      { label: "TP3", price: 4 },
    ],
    note: "TP1 no es el ATH (116 B)",
    cycleFit: 4,
  },
  {
    ticker: "RAY",
    symbol: "RAYUSDT",
    digits: 3,
    invalidation: null,
    zones: [{ label: "Compra", low: 1.1, high: 1.25, pct: 70 }],
    tps: [
      { label: "TP1", price: 16.83 },
      { label: "TP2", price: 25 },
      { label: "TP3", price: 35 },
    ],
    note: "4,5 B → 9,5 B",
    cycleFit: 3,
  },
  {
    ticker: "ARB",
    symbol: "ARBUSDT",
    digits: 4,
    invalidation: 0.07,
    zones: [{ label: "Compra", low: 0.09, high: 0.11, pct: 70 }],
    tps: [
      { label: "TP1", price: 2.39 },
      { label: "TP2", price: 3.2 },
      { label: "TP3", price: 4 },
    ],
    note: "Unlocks",
    cycleFit: 2,
  },
  {
    ticker: "TAO",
    symbol: "TAOUSDT",
    digits: 1,
    invalidation: null,
    zones: [{ label: "Compra", low: 180, high: 200, pct: 70 }],
    tps: [
      { label: "TP1", price: 758 },
      { label: "TP2", price: 1400 },
      { label: "TP3", price: 2000 },
    ],
    note: "FDV ~2×",
    cycleFit: 4,
  },
  {
    ticker: "HBAR",
    symbol: "HBARUSDT",
    digits: 5,
    invalidation: null,
    zones: [{ label: "Compra", low: 0.055, high: 0.062, pct: 70 }],
    tps: [
      { label: "TP1", price: 0.57 },
      { label: "TP2", price: 0.8 },
      { label: "TP3", price: 1 },
    ],
    note: "25 B → 44 B",
    cycleFit: 4,
  },
  {
    ticker: "ASTER",
    symbol: "ASTERUSDT",
    digits: 3,
    invalidation: 0.39,
    zones: [
      { label: "Compra", low: 0.585, high: 0.62, pct: 30 },
      { label: "Add", low: 0.507, high: 0.507, pct: 40 },
      { label: "Pánico", low: 0.403, high: 0.403, pct: 30 },
    ],
    tps: [
      { label: "TP1", price: 2.41 },
      { label: "TP2", price: 4 },
      { label: "TP3", price: 5.5 },
    ],
    note: "Team cliff → 17 sep 2027 (atraso 12 m). Airdrop ~80 meses.",
    cycleFit: 2,
  },
  {
    ticker: "AAVE",
    symbol: "AAVEUSDT",
    digits: 2,
    invalidation: 70,
    zones: [{ label: "Compra", low: 90, high: 110, pct: 70 }],
    tps: [
      { label: "TP1", price: 662 },
      { label: "TP2", price: 950 },
      { label: "TP3", price: 1200 },
    ],
    note: "Empresa",
    cycleFit: 5,
  },
  {
    ticker: "ONDO",
    symbol: "ONDOUSDT",
    digits: 3,
    invalidation: 0.2,
    zones: [
      { label: "Compra", low: 0.32, high: 0.335, pct: 40 },
      { label: "Add", low: 0.29, high: 0.3, pct: 60 },
    ],
    tps: [
      { label: "TP1", price: 2.14 },
      { label: "TP2", price: 3.2 },
      { label: "TP3", price: 4.5 },
    ],
    note: "~49% circ / FDV alto",
    cycleFit: 3,
  },
  {
    ticker: "UNI",
    symbol: "UNIUSDT",
    digits: 3,
    invalidation: 3.8,
    zones: [{ label: "Compra", low: 4.8, high: 5.2, pct: 70 }],
    tps: [
      { label: "TP1", price: 44.92 },
      { label: "TP2", price: 65 },
      { label: "TP3", price: 80 },
    ],
    note: "Fee switch",
    cycleFit: 5,
  },
  {
    ticker: "ENA",
    symbol: "ENAUSDT",
    digits: 4,
    invalidation: 0.065,
    zones: [
      { label: "Starter", low: 0.138, high: 0.145, pct: 30 },
      { label: "Add", low: 0.08, high: 0.09, pct: 40 },
      { label: "Pánico", low: 0.07, high: 0.07, pct: 30 },
    ],
    tps: [
      { label: "TP1", price: 1.52 },
      { label: "TP2", price: 2.2 },
      { label: "TP3", price: 2.8 },
    ],
    note: "Diluye a 15 B",
    cycleFit: 2,
  },
  {
    ticker: "JUP",
    symbol: "JUPUSDT",
    digits: 4,
    invalidation: 0.135,
    zones: [
      { label: "Compra", low: 0.2, high: 0.22, pct: 40 },
      { label: "Add", low: 0.16, high: 0.17, pct: 60 },
    ],
    tps: [
      { label: "TP1", price: 2 },
      { label: "TP2", price: 3.2 },
      { label: "TP3", price: 4.5 },
    ],
    note: "~49% circ",
    cycleFit: 3,
  },
  {
    ticker: "AVAX",
    symbol: "AVAXUSDT",
    digits: 3,
    invalidation: 5.5,
    zones: [
      { label: "Starter", low: 7.0, high: 7.5, pct: 30 },
      { label: "Add", low: 6.1, high: 6.1, pct: 40 },
      { label: "Pánico", low: 5.68, high: 5.68, pct: 30 },
    ],
    tps: [
      { label: "TP1", price: 145 },
      { label: "TP2", price: 180 },
      { label: "TP3", price: 220 },
    ],
    note: "220 = 97 B, euforia L1",
    cycleFit: 4,
  },
  {
    ticker: "LINK",
    symbol: "LINKUSDT",
    digits: 3,
    invalidation: 6.9,
    zones: [
      { label: "Compra", low: 11.0, high: 11.3, pct: 40 },
      { label: "Add", low: 9.5, high: 10.3, pct: 60 },
    ],
    tps: [
      { label: "TP1", price: 52.7 },
      { label: "TP2", price: 80 },
      { label: "TP3", price: 110 },
    ],
    note: "No entrar en 11,55",
    cycleFit: 5,
  },
  {
    ticker: "RON",
    symbol: "RONINUSDT",
    digits: 4,
    invalidation: 0.044,
    zones: [
      { label: "Compra", low: 0.049, high: 0.056, pct: 40 },
      { label: "Add", low: 0.046, high: 0.047, pct: 60 },
    ],
    tps: [
      { label: "TP1", price: 4.45 },
      { label: "TP2", price: 6.7 },
      { label: "TP3", price: 8.9 },
    ],
    note: "ATH 4,45 → 3,4 B; diluye a 1 B. No perseguir > 0,063",
    cycleFit: 2,
  },
  {
    ticker: "LINEA",
    symbol: "LINEAUSDT",
    digits: 6,
    invalidation: 0.002,
    zones: [
      { label: "Starter", low: 0.0022, high: 0.0024, pct: 30 },
      { label: "Add", low: 0.0021, high: 0.00215, pct: 40 },
      { label: "Pánico", low: 0.00207, high: 0.00207, pct: 30 },
    ],
    tps: [
      { label: "TP1", price: 0.0467 },
      { label: "TP2", price: 0.07 },
      { label: "TP3", price: 0.093 },
    ],
    note: "ATH listing; ~34% circ / 72 B. No perseguir > 0,00287",
    cycleFit: 3,
  },
];
